/** Runtime env for Netlify functions (avoids esbuild inlining + supports build-baked secrets). */

let privateEnv = {}
try {
  // Generated by scripts/write-function-secrets.mjs during Netlify build.
  privateEnv = require('./private-env.cjs')
} catch {
  privateEnv = {}
}

function pick(name, aliases = []) {
  const keys = [name, ...aliases]
  for (const key of keys) {
    const value = process.env[key] ?? privateEnv[key]
    if (value != null && String(value).trim()) return String(value).trim()
  }
  return ''
}

function loadRuntimeEnv() {
  const googleKey = pick('GOOGLE_TRANSLATE_API_KEY', ['GOOGLE_CLOUD_TRANSLATE_API_KEY', 'GOOGLE_API_KEY'])
  const serviceKey = pick('SUPABASE_SERVICE_ROLE_KEY', ['SUPABASE_SERVICE_KEY'])
  const supabaseUrl = pick('SUPABASE_URL', ['VITE_SUPABASE_URL'])
  const anonKey = pick('SUPABASE_ANON_KEY', ['VITE_SUPABASE_ANON_KEY'])

  return {
    ...process.env,
    ...(googleKey
      ? { GOOGLE_TRANSLATE_API_KEY: googleKey, GOOGLE_CLOUD_TRANSLATE_API_KEY: googleKey }
      : {}),
    ...(serviceKey ? { SUPABASE_SERVICE_ROLE_KEY: serviceKey } : {}),
    ...(supabaseUrl ? { SUPABASE_URL: supabaseUrl, VITE_SUPABASE_URL: supabaseUrl } : {}),
    ...(anonKey ? { SUPABASE_ANON_KEY: anonKey, VITE_SUPABASE_ANON_KEY: anonKey } : {}),
  }
}

module.exports = { loadRuntimeEnv }
