// Natural questions, abbreviations and synonyms supplement the existing phrases.
// Answer text remains in the authored KB. Keep uncertain terms out of this map.
export const QUESTION_VARIANTS = {
  vi: {
    services: ['ICUE cung cấp những dịch vụ gì', 'bên mình làm những gì'],
    planning_design: ['tư vấn thiết kế đô thị', 'tôi muốn quy hoạch khu đất', 'lập đồ án quy hoạch'],
    project_management: ['QLDA', 'điều phối dự án', 'quản lí dự án'],
    supervision: ['TVGS', 'tư vấn giám sát thi công', 'giám sát công trình'],
    permits_legal: ['GPXD', 'hỗ trợ giấy phép xây dựng', 'thủ tục xin phép xây dựng'],
    documents_required: ['cần chuẩn bị hồ sơ gì cho dự án', 'cần giấy tờ gì', 'tôi cần gửi những tài liệu nào'],
    pricing_fees: ['giá tư vấn bao nhiêu', 'chi phí thuê tư vấn', 'xin báo giá dịch vụ'],
    timeline_duration: ['mất bao lâu', 'thời gian thực hiện dự án', 'bao lâu thì xong'],
    process_steps: ['bắt đầu hợp tác như thế nào', 'các bước triển khai dự án'],
    bim_3d: ['mô hình thông tin công trình', 'phối hợp mô hình BIM'],
    green_sustainability: ['giải pháp tiết kiệm năng lượng', 'thiết kế thích ứng khí hậu'],
    recruitment: ['hồ sơ ứng tuyển cần gì', 'nộp CV ở đâu', 'các vị trí đang tuyển'],
    internship: ['hồ sơ thực tập cần gì', 'tôi là sinh viên muốn thực tập'],
    schedule_meeting: ['đặt lịch trao đổi với ICUE', 'hẹn gặp tư vấn'],
    request_proposal: ['RFP', 'gửi yêu cầu đề xuất', 'brief dự án cần những gì'],
  },
  en: {
    services: ['what can ICUE help me with', 'what services does ICUE offer'],
    planning_design: ['urban design consultancy', 'help planning a site', 'master planning'],
    project_management: ['project coordination', 'manage my project', 'PM consultancy'],
    supervision: ['construction site supervision', 'construction oversight'],
    permits_legal: ['building permit assistance', 'help with construction permits'],
    documents_required: ['what documents do I need for my project', 'what paperwork should I prepare', 'which documents should I send'],
    pricing_fees: ['how much does consulting cost', 'consultancy fees', 'cost estimate for services'],
    timeline_duration: ['how long does a project take', 'how long does it take', 'project turnaround time'],
    process_steps: ['how do we get started', 'steps to work with ICUE'],
    bim_3d: ['building information modelling', 'building information modeling', '3D visualization'],
    green_sustainability: ['energy efficient design', 'climate resilient design'],
    recruitment: ['what documents do I need to apply for a job', 'where do I send my CV', 'open job positions'],
    internship: ['what documents do I need for an internship', 'student placement'],
    schedule_meeting: ['book a consultation', 'arrange a call with ICUE'],
    request_proposal: ['RFP', 'request for proposal', 'what should a project brief include'],
  },
  de: {
    planning_design: ['Stadtplanung und Gestaltung', 'Masterplanung'],
    project_management: ['Projektkoordination', 'Projektsteuerung'],
    supervision: ['Bauüberwachung', 'Baustellenaufsicht'],
    permits_legal: ['Hilfe bei der Baugenehmigung'],
    documents_required: ['welche Unterlagen brauche ich für mein Projekt', 'welche Dokumente soll ich vorbereiten'],
    pricing_fees: ['wie viel kostet die Beratung', 'Beratungskosten'],
    timeline_duration: ['wie lange dauert ein Projekt', 'Bearbeitungsdauer'],
    process_steps: ['wie beginnen wir die Zusammenarbeit'],
    bim_3d: ['Building Information Modeling', 'Gebäudedatenmodellierung'],
    recruitment: ['welche Unterlagen brauche ich für eine Bewerbung', 'wohin sende ich meinen Lebenslauf'],
    internship: ['Unterlagen für ein Praktikum'],
    request_proposal: ['RFP', 'Angebotsanfrage'],
  },
  fr: {
    planning_design: ['conception urbaine', 'planification urbaine'],
    project_management: ['coordination de projet', 'pilotage de projet'],
    supervision: ['surveillance de chantier'],
    permits_legal: ['aide au permis de construire'],
    documents_required: ['quels documents préparer pour mon projet', 'quelles pièces dois-je fournir'],
    pricing_fees: ['combien coûte le conseil', 'tarifs de conseil'],
    timeline_duration: ['combien de temps dure un projet', 'délai de réalisation'],
    process_steps: ['comment commencer à travailler ensemble'],
    bim_3d: ['maquette numérique du bâtiment', 'Building Information Modeling'],
    recruitment: ['quels documents pour postuler', 'où envoyer mon CV'],
    internship: ['dossier de candidature pour un stage'],
    request_proposal: ['RFP', 'demande de proposition'],
  },
  ko: {
    planning_design: ['도시 설계 자문', '도시계획 설계'],
    project_management: ['프로젝트 조정', '사업 관리'],
    supervision: ['건설 현장 감리'],
    permits_legal: ['건축 허가 지원'],
    documents_required: ['프로젝트에 필요한 서류는 무엇인가요', '어떤 자료를 준비해야 하나요'],
    pricing_fees: ['자문 비용이 얼마인가요'],
    timeline_duration: ['프로젝트는 얼마나 걸리나요'],
    process_steps: ['협업을 어떻게 시작하나요'],
    bim_3d: ['건설 정보 모델링', 'Building Information Modeling'],
    recruitment: ['입사 지원에 필요한 서류', '이력서는 어디로 보내나요'],
    internship: ['인턴 지원 서류'],
    request_proposal: ['RFP', '제안 요청서'],
  },
  ja: {
    planning_design: ['都市設計の相談', '都市計画設計'],
    project_management: ['プロジェクト調整', '事業管理'],
    supervision: ['建設現場の監理'],
    permits_legal: ['建築許可のサポート'],
    documents_required: ['プロジェクトに必要な書類は何ですか', 'どんな資料を準備すればよいですか'],
    pricing_fees: ['コンサルティングの費用はいくらですか'],
    timeline_duration: ['プロジェクトはどのくらいかかりますか'],
    process_steps: ['協力を始めるにはどうすればよいですか'],
    bim_3d: ['ビルディングインフォメーションモデリング', 'Building Information Modeling'],
    recruitment: ['応募に必要な書類', '履歴書の送付先'],
    internship: ['インターン応募書類'],
    request_proposal: ['RFP', '提案依頼書'],
  },
}
